name: 'To Reuse'
inputs:
  bento_file:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: 'To Reuse '
      shell: bash
      run: |
        cat ${{ inputs.bento_file }}
          
